name: dev to uat 
on: 
  pull_request:
    types: ['labeled']

jobs:
  ranalyzer:
    if: $${{ github.event.label.name == 'uat'}}
    name: Dev scanner
    runs-on: ubuntu-latest
    steps:
    - name: Setup python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy 
      run: |
        echo "review requested"
        echo "deploy to uat"
