name: dev to uat 
on: 
  pull_request:
    types: [synchronize,review_request]

jobs:
  ranalyzer:
    name: Dev scanner
    runs-on: ubuntu-latest
    steps:
    - name: Setup python env
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Analyze pr 
      id: rr_status
      working-directory: .github/rc
      run: python pr_analyzer.py ${{github.event.pull_request.number}} ${{ github.repository }} ${{ github.ref }} ${{ secrets.GATK }} -rr

    - name: Deploy 
      if: ${{ steps.rr_status.outcome == 'success' && github.ref != 'refs/heads/main' }}
      run: |
        echo "review requested"
        echo "deploy to uat"
