name: deploy to uat 
on: 
  pull_request:
    types: [review_request]

jobs:
  ranalyzer:
    name: branch scanner dev 
    runs-on: ubuntu-latest
    if: $${{github.actor != 'photon-g'}}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan
      run: |
        echo "review requested" 
        ls -l
