name: scan uat branch 
on: 
  pull_request_target:
    types: 
      - review_requested

jobs:
  analyzer:
    if: $${{github.event.pull_request.review_requested == true }} || $${github.actor == 'photon-g'}}
    name: branch scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan repo
      run: |
        echo "scanning the repo" 
        ls -l
