name: scan uat branch 
on: 
  pull_request:
    types: [opened,reopened,review_requested]

jobs:
  analyzer:
    name: branch scanner 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan repo
      if: {{github.repository_owner == github.actor && github.event.pull_request.opened == true }} 
      run: |
        echo $${ github.event.pull_request.opened }}
        echo $${ github.event.pull_request.reopened }}
        echo $${ github.event.pull_request.reopened }}
        ls -l

    - name: Scan status
      if: {{github.event.pull_request.review_requested == true }}
      run: 
        echo "detected the right status" 


    - name: Setup building context
      working-directory: .github/rc
      shell: bash
      run: |
        ls -l 
        echo "testing action ..."
        ./context.sh
