name: scan uat branch 
on: 
  pull_request_target:
    types: [opened,review_requested]

jobs:
  analyzer:
    name: branch scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan repo
    - if: $${{github.event.pull_request_target.opened == true }} || $${github.actor == 'photon-g'}}
      run: |
        echo "opened by photon-g" 
        ls -l
